apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:  
  name: hello-pipeline
spec:
  params:
   - name: message
  tasks:
   - name: hello
     taskRef: 
       name: echo
     params:
       - name: message
         value: "$(params.message)"